{
  "excludeFiles": [
    "**/modLib/DebugHelper.lua",
    "**/modLib/GlobalHelper.lua",
    "**/modLib/FillTypeManagerExtension.lua",
    "**/modLib/AnimalFoodExtension.lua",
    "**/modLib/MathHelper.lua",
    "**/modLib/StoreItemExtension.lua",
    "**/modLib/StoreManagerExtension.lua",
    "**/modLib/CRC32.lua",
    "**/modLib/AnimalFoodExtension.lua",
    "**/modLib/FillTypeManagerExtension.lua",
    "**/modLib/GlobalHelper.lua",
    "**/modLib/I3DWriter.lua",
    "**/modLib/LinkedPlaceableSpecialization_full.lua",
    "**/modLib/LinkedPlaceableSpecialization.lua",
    "**/modLib/MathHelper.lua",
    "**/modLib/MeshBuilder.lua",
    "**/modLib/placeable.xsd",
    "**/modLib/PseudoRandom.lua",
    "**/modLib/StoreItemExtension.lua",
    "**/modLib/StoreManagerExtension.lua",
    "**/modLib/DevHelper.lua",
    "**/modLib/DialogHelper.lua",
    "**/modLib/EnhancedPlaceableSpecialization.lua",
    "**/modLib/Enumerable.lua",
    "**/modLib/I3DWriter.lua",
    "**/modLib/MemoryProfiler.lua",
    "**/modLib/MultistateKeyHandler.lua",
    "**/modLib/StringWriter.lua",
    "**/modLib/VehicleWorkshop.lua",
    "**/modLib/UIHelper.lua",
    "**/*.pdn",
    "**/*.bak",
    "**/*.md",
    "**/*.png",
    "FS25_DestructableObjects/xml/dummyObject.xml",
    "**/dummyObject3.i3d*",
    "**/clearAreas.i3d*",
    "**/destructibleRocksL_paint.xml",
    "**/language_LANGCODE.xml",
    "**/destructibleRocksS.*",
    "**/destructibleRocksM.*",
    "**/PlaceableDestructibleMapObjectSystem.lua"
  ],
  "autoBumpModDescVersion": true,
  "name": "FS25_DestructableObjects"
}